#
# Module manifest for module 'Proxx'
#
# Generated by: Marco v. G. (Proxx)
#
# Generated on: 10-2-2015
#

@{

# Script module or binary module file associated with this manifest.
#RootModule = ''

# Version number of this module.
ModuleVersion = '0.9.0.150'

# ID used to uniquely identify this module
GUID = '1c192038-d361-43e4-a7e6-b5e317de7bcf'

# Author of this module
Author = 'Marco van Gaal'

# Company or vendor of this module
CompanyName = 'Proxx.nl'

# Copyright statement for this module
Copyright = '(c) 2015 Proxx.nl. All rights reserved.'

# Description of the functionality provided by this module
# Description = 'Module contains Nested module each for different purposes, Proxx.Default has miscellaneous functions. the rest is self explaned (e.g. Proxx.SQLite has functions for SQLite)'

# Minimum version of the Windows PowerShell engine required by this module
# PowerShellVersion = '4.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = '4.0'

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
#RequiredAssemblies = @('')

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('./Common.Proxx/Common.Proxx.psd1','./SNMP.Proxx/SNMP.Proxx.psd1', './Network.Proxx/Network.Proxx.psd1', './SQLite.Proxx/SQlite.Proxx.psd1')

# Functions to export from this module
FunctionsToExport = '*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = @('Proxx.psm1','Proxx.psd1','./Common.Proxx/Common.Proxx.psd1','./Common.Proxx/Common.Proxx.psm1','./SNMP.Proxx/SNMP.Proxx.psd1','./SNMP.Proxx/SNMP.Proxx.psm1', './Network.Proxx/Network.Proxx.psd1', './Network.Proxx/Network.Proxx.psm1', './SQLite.Proxx/SQlite.Proxx.psd1', './SQLite.Proxx/SQlite.Proxx.psm1','./Network.Proxx/MySql.Data.dll','./SNMP.Proxx/SnmpSharpNet.dll','./SQLite.Proxx/SQLite.Interop.dll','./SQLite.Proxx/System.Data.SQLite.dll')

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

