#
# Module 'Proxx.SNMP'
#
# Generated by: Marco van Gaal
# Generated on: 10-5-2015
#
# Website: www.proxx.nl
#
#### Depends on SnmpSharpNet from http://www.snmpsharpnet.com/

Resolve-Path -Path $PSScriptRoot\*.ps1 | ForEach-Object { . $_.ProviderPath }
Set-Alias -Name SnmpGet -Value Invoke-SnmpGet
Set-Alias -Name SnmpWalk -Value Invoke-SnmpWalk

Export-ModuleMember -Function Invoke-SnmpGet, Invoke-SnmpWalk -Alias SnmpGet, SnmpWalk



